### ISSUE TITLE
is there any example project?

### ISSUE THREAD

**Issue by diybl** [Carnagion/Modot#11]
useing godot 4 may some example code is error.

**Comment by Carnagion** [comment]
Modot isn't compatible with Godot 4 just yet; it can only be used with Godot 3.5.
Check out https://github.com/Carnagion/Pong for an example project and walkthrough.

Modot will eventually be compatibile with Godot 4. However, this will take some time, as I am the sole developer working on this project. You are free to help out and make contributions to Modot if you'd like.

There is also an ongoing merge request (#10) to introduce GDScript to Modot, which will let you use the GDScript release of Modot with Godot 4. However, this will also take a while to merge as recent RCs have introduced many changes.

**Comment by diybl** [comment]
> useing godot 4 may some example code is error.

do u solve this problem?
https://docs.godotengine.org/en/latest/tutorials/export/exporting_pcks.html

**Comment by diybl** [comment]
I have a similar issue where I have a base project (let's call it Base) exported as runnable, and a second project (lets call it Addon) exported as .pck.
Addon project contains a "MyAddon.tscn" simple node and a "MyAddon.cs".

Then I bundle everything, the setup being

Base.pck
Base.dll
data_Base/
Addon.pck
Addon.dll
But even by loading the Addon.dll assembly by hand, following pck, trying to instantiate a node in the Addon.pck won't work with the same error:

    Assembly.LoadFrom("Addon.dll");
    // Here, dll is correctly loaded with all my C# scripts
    ProjectSettings.LoadResourcePack("Addon.pck");
   // Looking into the available resources with a Godot.Directory does list MyAddon.tscn and MyAddon.cs
    var scene = ResourceLoader.Load<PackedScene>("res://MyAddon.tscn");
    var node = scene.Instance(); // Failure
ERROR: Cannot instance script because the class 'MyAddon.cs' could not be found. Script: 'res://MyAddon.cs'.
   At: modules/mono/csharp_script.cpp:2942
Is there a workaround for this ? Can I somehow tell Godot the class does exists in the loaded assembly ?
Note:
I tried loading my Base script, and it loads with the SourceCode field of the CSharpClass filled with the source code.
But doing ResourceLoader.Load("res://MyAddon.cs"); does return a valid c# but with the SourceCode field empty...
Given that the Addon.cs code is bundled into another assembly, I hope the trick is not to export the source code "clear" so it can be run by the Base project ...

**Comment by Carnagion** [comment]
What Godot version are you using? And please include a minimal reproducible example project so I can check what the actual issue is.

**Comment by diybl** [comment]
https://github.com/godotengine/godot/issues/74146
https://github.com/godotengine/godot/issues/73932
73932 issues has been contain
the godot member say the problem is the same with 73932

**Comment by Carnagion** [comment]
These seem to be Godot 4 issues.
I reiterate that **Modot is NOT compatible with Godot 4**.

I will not be fixing any issues that arise with using Modot and Godot 4 until I actually port Modot over to Godot 4.

**Comment by diybl** [comment]
it looks like the godot 4 bug may be not solved by the costomers. it is the engine's bug.
