### ISSUE TITLE
Contribution guide

### ISSUE THREAD

**Issue by TrustNoOneElse** [Carnagion/Modot#12]
Hey there,
i really like how Modot is structured and wanted to help to migrate it to godot 4 for c# for my personal project. But there is no contribution guide yet and i would love to have one :)

**Comment by Carnagion** [comment]
Hello! Thanks for expressing your interest in contributing.
I'll set up a `CONTRIBUTING.md` file in the coming days.
In the meantime, feel free to familiarize yourself with the codebase or open any PRs :)

**Comment by TrustNoOneElse** [comment]
Thank you for setting it up! :)
Im getting familiar with it in the meantime and looking what i need to change all, since you have a very nice modular structure with your other projects :)

**Comment by Carnagion** [comment]
As requested, I have now added a contribution guide as well as a few issue templates (#14 and #15).
Feel free to have a look and clarify any doubts that might arise.

**Comment by TrustNoOneElse** [comment]
Thank you for adding it so fast! I have one doubt, in the section making changes, you link to create a new issue, it does not use the template for enhancement and feature, is that correct? The other parts are understandable :)

**Comment by Carnagion** [comment]
It depends on the template. If your contribution is for fixing bugs, then you would use the bug report issue template. If it's adding a new feature, then you would use the feature report template.
Alternatively, you can use the blank template for a more customised issue.
